name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install npm packages
        run: npm ci
      - name: Setup Git
        run: |
          git config user.name 'Sergio Xalambrí'
          git config user.email 'hello@sergiodxa.com'
      - name: bump version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: ["bump-version"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release Notes
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.request(`POST /repos/${{ github.repository }}/releases`, {
              tag_name: "${{ github.ref }}",
              generate_release_notes: true
            });
